config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  get 'about' => 'pages#about'
  get 'employers' => 'pages#company_home'
  get 'your-applications' => 'students#your_apply'
  get 'your-accepted-jobs' => 'students#your_accepted_job'
  get 'your-jobs' => 'companies#your_job'
  get 'your-applicants' => 'companies#your_applicant'
  get 'your-employee' => 'companies#your_employee'

  devise_for :companies
  devise_for :students

  resources :messages, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :registrations, only: [:new, :create]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :students do
    resource :resume, except: [:index, :show]
    resources :accepts, only: [:create]
    resources :feedbacks, except: [:show]
    collection do
      match 'search' => 'students#search', via: [:get, :post], as: :search
    end
  end

  resources :companies do
    resource :profile, except: [:index, :show]
    resources :reviews, except: [:show]
    collection do
      match 'search' => 'companies#search', via: [:get, :post], as: :search
    end
  end

  resources :jobs do
    resources :applies, only: [:create]
    collection do
      match 'search' => 'jobs#search', via: [:get, :post], as: :search
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_one :resume
  has_many :applies
  has_many :jobs, through: :applies
  has_many :accepts
  has_many :companies, through: :accepts
  has_many :feedbacks
  has_many :reviews

  acts_as_messageable

  def mailboxer_email(object)
   return email
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nim, presence: true, numericality: true, uniqueness: true
  
  def to_param
   "#{id}-#{first_name.parameterize}-#{last_name.parameterize}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!, only: [:your_apply, :your_accepted_job]
  before_action :authenticate_company!, only: [:index, :search]

  def index
    @search = Student.ransack(params[:q])
    @students = @search.result.includes(:resume).paginate(page: params[:page], per_page: 20)
  end

  def search
    index
    render :index
  end

  def show
    @student = Student.find(params[:id])

    if @student.feedbacks.blank?
      @average_feedback = 0
    else
      @average_feedback = @student.feedbacks.average(:rating).round(2)
    end
  end

  def your_apply
    @applies = current_student.applies
  end

  def your_accepted_job
    @accepts = current_student.accepts
  end
end

app/views/students/index.html.erb
<% provide(:title, "Browse Students") %>

<div class="search-student-section padding-top padding-bottom margin-bottom">
  <div class="container">
    <%= search_form_for @search, url: search_students_path, method: :post do |f| %>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.text_field :first_name_cont, placeholder: 'First Name', class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.text_field :last_name_cont, placeholder: 'Last Name', class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.select :resume_university_cont, university, { include_blank: 'University' }, class: 'selection form-control' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.select :resume_city_cont, city, { include_blank: 'City' }, class: 'selection form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.select :resume_province_cont, province, { include_blank: 'Province' }, class: 'selection form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group text-center" style="margin-top: -20px">
            <%= f.range_field :resume_gpa_gteq, in: 1..4, step: 0.1, id: 'gpa-slider', class: 'form-control' %>
            <strong style="color: #fff;">Minimum GPA: <%= f.label :resume_gpa_gteq, '...', id: 'value', class: 'label label-green' %></strong>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <%= f.submit 'Search Student', class: 'btn btn-lg btn-green' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @students.each do |student| %>
      <% if student.resume %>
      <div class="col-md-4 col-sm-6">
        <div class="panel panel-default">
          <div class="panel-heading text-center">
            <%= image_tag student.resume.photo.url(:profile), class: 'img-circle' %>
            <h4><%= student.first_name %> <%= student.last_name %></h4>
            <h5><label class="label label-green">GPA: <%= student.resume.gpa %></label></h5>
          </div>

          <div class="panel-body">
            <div class="col-sm-12">
              <p class="small"><strong>University:</strong> <%= student.resume.university %></p>
              <p class="small"><strong>Major:</strong> <%= student.resume.major %> | <%= student.resume.level %></p>
              <p class="small"><strong>Skills:</strong> <%= student.resume.skill_list %></p>
            </div>

            <div class="col-sm-6">
              <%= link_to 'Student Details', student, class: 'btn btn-block btn-green' %>
            </div>

            <div class="col-sm-6">
              <%= link_to 'Send Message', new_message_path(to: student.id), class: 'btn btn-block btn-yellow' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    <%= will_paginate @students %>
  </div>

</div>

app/views/students/show.html.erb
<% provide(:title, "#{@student.first_name} #{@student.last_name} Profile") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <%= image_tag @student.resume.photo.url(:profile), class: 'img-circle', style: 'border: 5px solid #fff;' %>
          <h3><strong><%= @student.first_name %> <%= @student.last_name %></strong></h3>
          <h5><strong><%= @student.resume.major %>, <%= @student.resume.university %></strong></h5>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-1 col-sm-offset-1">
              <%= icon('transgender', class: 'strong fa-3x') %>
            </div>

            <div class="col-sm-8 col-sm-offset-1">
              <h4 class="media-heading">Gender</h4>
              <%= @student.resume.gender %>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-sm-1 col-sm-offset-1">
              <%= icon('calendar-o', class: 'strong fa-3x') %>
            </div>

            <div class="col-sm-8 col-sm-offset-1">
              <h4 class="media-heading">Date of Birth</h4>
              <%= @student.resume.birth_date.strftime("%B %d, %Y") %>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-sm-1 col-sm-offset-1">
              <%= icon('map', class: 'strong fa-3x') %>
            </div>

            <div class="col-sm-8 col-sm-offset-1">
              <h4 class="media-heading">Address</h4>
              <%= @student.resume.address %><br>
              <%= @student.resume.city %>, <%= @student.resume.province %><br>
              <%= @student.resume.country %> (<%= @student.resume.postal_code %>)
            </div>
          </div>

          <hr>

          <div class="row">
            <% if @student.resume.facebook_url.present? %>
              <div class="col-sm-3 text-center">
                <%= link_to @student.resume.facebook_url do %>
                  <%= icon('facebook-square', class: 'strong fa-2x', style: 'color: #3b5998') %>
                <% end %>
              </div>
            <% end %>

            <% if @student.resume.twitter_url.present? %>
              <div class="col-sm-3 text-center">
                <%= link_to @student.resume.twitter_url do %>
                  <%= icon('twitter-square', class: 'strong fa-2x', style: 'color: #55acee') %>
                <% end %>
              </div>
            <% end %>

            <% if @student.resume.linkedin_url.present? %>
              <div class="col-sm-3 text-center">
                <%= link_to @student.resume.linkedin_url do %>
                  <%= icon('linkedin-square', class: 'strong fa-2x', style: 'color: #0077B5') %>
                <% end %>
              </div>
            <% end %>

            <% if @student.resume.googleplus_url.present? %>
              <div class="col-sm-3 text-center">
                <%= link_to @student.resume.googleplus_url do %>
                  <%= icon('google-plus-square', class: 'strong fa-2x', style: 'color: #d34836') %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

        <% if current_company %>

          <div class="panel-footer text-center">
            <%= link_to 'Send Message', new_message_path(to: @student.id), class: 'btn btn-yellow' %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h3><strong>Details</strong></h3>
        </div>

        <div class="panel-body">
          <h4><strong>About me:</strong></h4>
          <%= simple_format(@student.resume.description) %>

          <hr>

          <h4><strong>Education:</strong></h4>
          <strong>University:</strong> <%= @student.resume.university %><br>
          <strong>Major:</strong> <%= @student.resume.major %><br>
          <strong>Level:</strong> <%= @student.resume.level %><br>
          <strong>Graduation Year:</strong> <%= @student.resume.grad_year.strftime("%Y") %><br>
          <strong>GPA/IPK:</strong> <%= @student.resume.gpa %><br>

          <hr>

          <h4><strong>Skills:</strong></h4>
          <%= @student.resume.skill_list %>

          <hr>

          <h4><strong>Languages:</strong></h4>
          <%= @student.resume.language_list %>

          <% if @student.resume.experiences.present? %>
            <hr>

            <h4><strong>Work experiences:</strong></h4>
            <% @student.resume.experiences.each do |exp| %>
              <div class="row">
                <div class="col-sm-12">
                  <strong>Company Name:</strong> <%= exp.company_name %><br>
                  <strong>Position:</strong> <%= exp.position %><br>
                  <strong>Time Period:</strong> <%= exp.start_work.strftime("%B %Y") %> -
                  <% if exp.is_current == true %>
                     now
                  <% else %>
                    <%= exp.end_work.strftime("%B %Y") %>
                  <% end %><br>
                  <strong>Description:</strong><br>
                  <%= simple_format(exp.description) %>
                </div>
              </div>
              <br>
            <% end %>
          <% end %>

          <% if @student.resume.portfolios.present? %>
            <hr>

            <h4><strong>Portfolios:</strong></h4>
            <% @student.resume.portfolios.each do |port| %>
              <div class="row">
                <div class="col-sm-12">
                  <strong>Portfolio Name:</strong> <%= port.title %><br>
                  <strong>URL:</strong> <%= link_to port.link do %><%= port.link %><% end %><br>
                  <strong>Description:</strong><br>
                  <%= simple_format(port.description) %>
                </div>
              </div>
              <br>
            <% end %>
          <% end %>

          <% if @student.feedbacks.present? %>
            <hr>

            <h4><strong>Feedbacks:</strong></h4>

            <div class="row">
              <div class="col-sm-4">
                <strong>Average Feedback:</strong>
                <div class="average-feedback-rating" data-score="<%= @average_feedback %>"></div>
                <small>Based on <%= @student.feedbacks.count %> feedbacks</small><br>
                <small><%= link_to 'See all feedbacks', student_feedbacks_path(@student) %></small>
              </div>

              <div class="col-sm-8">
                <% @student.feedbacks.each do |feedback| %>
                  <div class="feedback-rating" data-score="<%= feedback.rating %>"></div>
                  <strong>Feedback from <%= feedback.company.company_name %></strong>
                  <p><%= simple_format(feedback.comment) %></p>

                  <% if company_signed_in? %>
                    <% if feedback.company_id == current_company.id %>
                      <%= link_to 'Edit', edit_student_feedback_path(feedback.student, feedback) %> |
                      <%= link_to 'Delete', student_feedback_path(feedback.student, feedback), method: :delete,
                      data: {confirm: 'Are you sure?'} %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.feedback-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: ""
  });
</script>

<script>
  $('.average-feedback-rating').raty({
    readOnly: true,
    path: "",
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/students/your_accepted_job.html.erb
<% provide(:title, "My Accepted Jobs") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h2>Job List</h2>
        </div>
        <div class="panel-body">
          <% @accepts.each do |accept| %>
          <div class="row">
            <div class="col-sm-3">
              <%= image_tag accept.job.company.profile.logo.url(:small) %>
            </div>

            <div class="col-sm-9">
              <strong><%= accept.job.job_title %> at <%= accept.job.company.company_name %></strong>
              <br>
              <label class="label label-<%= accept.job.job_type.delete(' ').downcase %>"><%= accept.job.job_type %></label> |
              <label class="label label-<%= accept.job.urgency.delete(' ').downcase %>"><%= accept.job.urgency %></label> |
              <% if accept.job.is_paid == true %>
                <label class="label label-green">Paid</label>
              <% else %>
                <label class="label label-blue">No paid</label>
              <% end %>
              <div class="small-gap"></div>
              <%= link_to 'Job Details', accept.job, class: 'btn btn-green' %>
              <%= link_to 'Send Message', new_message_path(to: accept.job.company.id), class: 'btn btn-yellow' %>
              <%= link_to 'Give Review', new_company_review_path(accept.job.company.id), class: 'btn btn-red' unless
              Review.where(company_id: accept.job.id, student_id: current_student.id).present? %>
            </div>
          </div>
          <hr>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'layouts/studentsidebar' %>
    </div>
  </div>
</div>

app/views/students/your_apply.html.erb
<% provide(:title, "My Application List") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h2>Application List</h2>
        </div>

        <div class="panel-body">
          <% @applies.each do |apply| %>
            <div class="row">
              <div class="col-sm-3">
                <%= image_tag apply.job.company.profile.logo.url(:small) %>
              </div>

              <div class="col-sm-9">
                <strong><%= apply.job.job_title %> at <%= apply.job.company.company_name %></strong>
                <br>
                <label class="label label-<%= apply.job.job_type.delete(' ').downcase %>"><%= apply.job.job_type %></label> |
                <label class="label label-<%= apply.job.urgency.delete(' ').downcase %>"><%= apply.job.urgency %></label> |
                <% if apply.job.is_paid == true %>
                  <label class="label label-green">Paid</label>
                <% else %>
                  <label class="label label-blue">No paid</label>
                <% end %>
                <div class="small-gap"></div>
                <%= link_to 'Job Details', apply.job, class: 'btn btn-green' %>
                <%= link_to 'Send Message', new_message_path(to: apply.job.company.id), class: 'btn btn-yellow' %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'layouts/studentsidebar' %>
    </div>
  </div>
</div>