config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  get 'about' => 'pages#about'
  get 'employers' => 'pages#company_home'
  get 'your-applications' => 'students#your_apply'
  get 'your-accepted-jobs' => 'students#your_accepted_job'
  get 'your-jobs' => 'companies#your_job'
  get 'your-applicants' => 'companies#your_applicant'
  get 'your-employee' => 'companies#your_employee'

  devise_for :companies
  devise_for :students

  resources :messages, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :registrations, only: [:new, :create]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :students do
    resource :resume, except: [:index, :show]
    resources :accepts, only: [:create]
    resources :feedbacks, except: [:show]
    collection do
      match 'search' => 'students#search', via: [:get, :post], as: :search
    end
  end

  resources :companies do
    resource :profile, except: [:index, :show]
    resources :reviews, except: [:show]
    collection do
      match 'search' => 'companies#search', via: [:get, :post], as: :search
    end
  end

  resources :jobs do
    resources :applies, only: [:create]
    collection do
      match 'search' => 'jobs#search', via: [:get, :post], as: :search
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_member!
  before_action :get_mailbox
  before_action :get_box, only: [:index]
  before_action :get_conversation, except: [:index, :empty_trash]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show

  end

  def reply
    current_member.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_member)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_member)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_member).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_member)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    if(member_signed_in?)
      @mailbox ||= current_member.mailbox
    else
      redirect_to conversation_path(conversation)
    end
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_member) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-blue', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-red', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/index.html.erb
<% provide(:title, "Message Center") %>

<div class="container margin-top margin-bottom">
  <div class="col-md-8">
    <div class="panel panel-green">
      <div class="panel-heading text-center">
        <h2>Message Center</h2>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-sm-3">
            <ul class="nav nav-pills nav-stacked">
              <%= mailbox_section 'inbox', @box %>
              <%= mailbox_section 'sent', @box %>
              <%= mailbox_section 'trash', @box %>
            </ul>
          </div>

          <div class="col-sm-9">
            <% if @box == 'trash' %>
             <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-red', method: :delete,
                            data: {confirm: 'Are you sure?'} %></p>
            <% end %>
            <ul class="list-group">
              <%= render partial: 'conversations/conversation', collection: @conversations %>
            </ul>

            <%= will_paginate %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <% if student_signed_in? %>
      <%= render 'layouts/studentsidebar' %>
    <% elsif company_signed_in? %>
      <%= render 'layouts/companysidebar' %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<% provide(:title, "Message Center") %>

<div class="container margin-top margin-bottom">
  <div class="col-md-8">
    <div class="panel panel-green">
      <div class="panel-heading text-center">
        <h2><%= @conversation.subject %></h2>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-sm-3">
            <ul class="nav nav-pills nav-stacked">
              <%= mailbox_section 'inbox', @box %>
              <%= mailbox_section 'sent', @box %>
              <%= mailbox_section 'trash', @box %>
            </ul>
          </div>

          <div class="col-sm-9">
            <div class="messages">
              <% @conversation.receipts_for(current_member).each do |receipt| %>
                <% message = receipt.message %>

                <p><strong><%= message.sender.first_name %> <%= message.sender.last_name %></strong> sent message at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></p>

                <p><%= message.body %></p>

                <hr>
              <% end %>

              <%= form_tag reply_conversation_path(@conversation), method: :post do %>
                <div class="form-group">
                  <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
                </div>
                <%= submit_tag "Send Message", class: 'btn btn-green' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <% if student_signed_in? %>
      <%= render 'layouts/studentsidebar' %>
    <% elsif company_signed_in? %>
      <%= render 'layouts/companysidebar' %>
    <% end %>
  </div>
</div>