config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  get 'about' => 'pages#about'
  get 'employers' => 'pages#company_home'
  get 'your-applications' => 'students#your_apply'
  get 'your-accepted-jobs' => 'students#your_accepted_job'
  get 'your-jobs' => 'companies#your_job'
  get 'your-applicants' => 'companies#your_applicant'
  get 'your-employee' => 'companies#your_employee'

  devise_for :companies
  devise_for :students

  resources :messages, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :registrations, only: [:new, :create]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :students do
    resource :resume, except: [:index, :show]
    resources :accepts, only: [:create]
    resources :feedbacks, except: [:show]
    collection do
      match 'search' => 'students#search', via: [:get, :post], as: :search
    end
  end

  resources :companies do
    resource :profile, except: [:index, :show]
    resources :reviews, except: [:show]
    collection do
      match 'search' => 'companies#search', via: [:get, :post], as: :search
    end
  end

  resources :jobs do
    resources :applies, only: [:create]
    collection do
      match 'search' => 'jobs#search', via: [:get, :post], as: :search
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_one :profile
  has_many :jobs
  has_many :applies, through: :jobs
  has_many :accepts
  has_many :students, through: :accepts
  has_many :feedbacks
  has_many :reviews

  acts_as_messageable

  def mailboxer_email(object)
   return email
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company_name, presence: true
  validates :phone_number, presence: true, numericality: true, uniqueness: true

  def to_param
   "#{id}-#{company_name.parameterize}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController <ApplicationController
  before_action :authenticate_company!, only: [:your_job, :your_applicant]
  before_action :only_current_company, only: [:show]

  def index
    @search = Company.ransack(params[:q])
    @companies = @search.result.includes(:profile).paginate(page: params[:page], per_page: 20)
  end

  def search
    index
    render :index
  end

  def show
    @company = Company.find(params[:id])

    if @company.reviews.blank?
     @average_review = 0
    else
     @average_review = @company.reviews.average(:rating).round(2)
    end
  end

  def your_job
    @jobs = current_company.jobs
  end

  def your_applicant
    @applicants = current_company.applies
  end

  def your_employee
    @employees = current_company.accepts
  end

  private
    def only_current_company
      @company = Company.find(params[:id])
      @profile = @company.profile
    end
end

app/views/companies/index.html.erb
<% provide(:title, "Browse Companies") %>

<div class="search-company-section padding-top padding-bottom margin-bottom">
  <div class="container">
    <div class="row">
      <%= search_form_for @search, url: search_companies_path, method: :post do |f| %>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.search_field :company_name_cont, placeholder: 'Company Name', class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.select :profile_field_cont, field, { include_blank: 'Industry' }, class: 'selection form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.select :profile_province_cont, province, { include_blank: 'Province' }, class: 'selection form-control' %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <%= f.submit 'Search Company', class: 'btn btn-lg btn-green' %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @companies.each do |company| %>
      <% if company.profile %>
        <div class="col-md-4 col-sm-6">
          <div class="panel panel-green">
            <div class="panel-body">
              <div class="row">
                <div class="col-sm-12 text-center">
                  <%= image_tag company.profile.logo.url(:medium), style: 'max-width: 80%' %>
                  <h4><strong><%= company.company_name %></strong></h4>
                  <h5><%= company.profile.field %></h5>

                  <hr>

                  <%= company.profile.description.truncate(300, separator: /\s/) %>

                  <div class="small-gap"></div>

                  <%= link_to 'Company Details', company, class: 'btn btn-block btn-green' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= will_paginate @companies %>
  </div>

</div>

app/views/companies/show.html.erb
<div class="container margin-top margin-bottom">
  <div class="col-md-4">
    <div class="panel panel-green">
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-12 text-center">
            <%= image_tag @company.profile.logo.url(:medium), sytle: 'max-width: 80%' %>
            <h4><strong><%= @company.company_name %></strong></h4>
            <%= @company.profile.field %><br>
            <% if @company.profile.website.present? %>
              <%= link_to @company.profile.website do %>
                <%= @company.profile.website %>
              <% end %>
            <% end %>
          </div>
        </div>

        <hr>

        <div class="row">
          <div class="col-sm-12">
            <h4 class="media-heading">Headquarter:</h4>
            <%= @company.profile.address %><br>
            <%= @company.profile.city %>, <%= @company.profile.province %><br>
            <%= @company.profile.country %>
          </div>
        </div>

        <hr>

        <div class="row">
          <div class="col-sm-12">
            <h4 class="media-heading">Average Review from students:</h4>
            <div class="average-review-rating" data-score="<%= @average_review %>"></div>
            <small>Based on <%= @company.reviews.count %> reviews</small><br>
            <small><%= link_to 'See all reviews', company_reviews_path(@company) %></small>

            <% if current_student %>
              <% if @company.students.where('student_id = ?', current_student.id).present? %>
                <hr>
                <%= link_to 'Give Review', new_company_review_path(@company), class: 'btn btn-green' unless
                Review.where(company_id: @company.id, student_id: current_student.id).present? %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <% if current_company %>
        <% if @profile.company_id == current_company.id %>
          <div class="panel-footer">
              <%= link_to 'Edit Profile', edit_company_profile_path(current_company), class: 'btn btn-green' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-green">
      <div class="panel-heading text-center">
        <h3><strong>About the Company</strong></h3>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-sm-12">
            <h4 class="media-heading">About:</h4>
            <%= simple_format(@company.profile.description) %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-green">
      <div class="panel-heading text-center">
        <h3><strong>Jobs Available</strong></h3>
      </div>

      <div class="panel-body">
        <% @company.jobs.each do |job| %>
          <div class="col-sm-6">
            <div class="panel panel-blue">
              <div class="panel-heading text-center">
                <h4><strong><%= job.job_title %></strong></h4>
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-sm-12 text-center">
                    <label class="label label-<%= job.job_type.delete(' ').downcase %>"><%= job.job_type %></label> |
                    <label class="label label-<%= job.urgency.delete(' ').downcase %>"><%= job.urgency %></label> |
                    <% if job.is_paid == true %>
                      <label class="label label-green">Paid</label>
                    <% else %>
                      <label class="label label-blue">No paid</label>
                    <% end %>
                  </div>
                </div>

                <div class="small-gap"></div>
                <div class="row">
                  <div class="col-sm-12">
                    <p class="small"><strong>Working location:</strong> <%= job.city %>, <%= job.province %></p>
                    <p class="small"><strong>Working period:</strong> <%= job.start_period.strftime("%B %Y") %> -
                    <% if is_flexible = true %>
                      No specific time.</p>
                    <% else %>
                      <%= job.end_period.strftime("%B %Y") %></p>
                    <% end %>
                    <p class="small"><strong>Dificulties:</strong> <%= job.difficulties %> Application</p>
                    <p class="small"><strong>Deadline:</strong> <%= job.deadline.strftime("%d %B %Y at %H:%M") %></p>
                    <%= link_to 'Job Details', job, class: 'btn btn-block btn-green' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: ""
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: "",
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/companies/your_applicant.html.erb
<% provide(:title, "Applicant List") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h2>Applicant List</h2>
        </div>

        <div class="panel-body">
          <% @applicants.each do |applicant| %>
            <div class="row">
              <div class="col-sm-2">
                <%= image_tag applicant.student.resume.photo.url(:thumb), class: 'img-circle' %>
              </div>

              <div class="col-sm-10">
                <strong>Name:</strong> <%= applicant.student.first_name %> <%= applicant.student.last_name %><br>
                <strong>Job Title:</strong> <%= applicant.job.job_title %><br>
                <strong>Job Type:</strong> <%= applicant.job.job_type %>

                <div class="small-gap"></div>

                <%= form_for([applicant.student, applicant.student.accepts.new]) do |f| %>
                  <%= f.hidden_field :student_id, value: applicant.student.id %>
                  <%= f.hidden_field :job_id, value: applicant.job.id %>
                  <%= f.submit 'Hire', class: 'btn btn-green', data: { confirm: 'You are about to hire this candidate. Are you sure?' } %>
                  <%= link_to 'Job Details', applicant.job, class: 'btn btn-blue' %>
                  <%= link_to 'Applicant Details', applicant.student, class: 'btn btn-red' %>
                  <%= link_to 'Send Message', new_message_path(to: applicant.student.id), class: 'btn btn-yellow' %>
                <% end %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'layouts/companysidebar' %>
    </div>
  </div>
</div>

app/views/companies/your_employee.html.erb
<% provide(:title, "Hired List") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h2>Hired List</h2>
        </div>

        <div class="panel-body">
          <% @employees.each do |employee| %>
            <div class="row">
              <div class="col-sm-2">
                <%= image_tag employee.student.resume.photo.url(:thumb), class: 'img-circle' %>
              </div>

              <div class="col-sm-10">
                <strong>Name:</strong> <%= employee.student.first_name %>  <%= employee.student.last_name %><br>
                <strong>Job Title:</strong> <%= employee.job.job_title %><br>
                <strong>Job Type:</strong> <%= employee.job.job_type %>

                <div class="small-gap"></div>

                <%= link_to 'Job Details', employee.job, class: 'btn btn-blue' %>
                <%= link_to 'Applicant Details', employee.student, class: 'btn btn-red' %>
                <%= link_to 'Send Message', new_message_path(to: employee.student.id), class: 'btn btn-yellow' %>
                <%= link_to 'Give Feedback', new_student_feedback_path(employee.student.id), class: 'btn btn-green' unless
                Feedback.where(company_id: current_company.id, student_id: employee.student.id).count > 0 %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'layouts/companysidebar' %>
    </div>
  </div>
</div>

app/views/companies/your_job.html.erb
<% provide(:title, "Job List") %>

<div class="container margin-top margin-bottom">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-green">
        <div class="panel-heading text-center">
          <h2>Job List</h2>
        </div>

        <div class="panel-body">
          <% @jobs.each do |job| %>
            <div class="row">
              <div class="col-sm-3">
                <%= image_tag job.company.profile.logo.url(:small) %>
              </div>

              <div class="col-sm-9">
                <strong><%= job.job_title %></strong>
                <br>
                <label class="label label-<%= job.job_type.delete(' ').downcase %>"><%= job.job_type %></label> |
                <label class="label label-<%= job.urgency.delete(' ').downcase %>"><%= job.urgency %></label> |
                <% if job.is_paid == true %>
                  <label class="label label-green">Paid</label>
                <% else %>
                  <label class="label label-blue">No paid</label>
                <% end %>
                <div class="small-gap"></div>

                <p class="small"><strong>Working period:</strong> <%= job.start_period.strftime("%B %Y") %> - <%= job.start_period.strftime("%B %Y") %>
                <br>
                <strong>Deadline:</strong> <%= job.deadline.strftime("%d %B %Y at %H:%M") %></p>

                <%= link_to 'Edit Job', edit_job_path(job), class: 'btn btn-green' %>
                <%= link_to 'Job Details', job, class: 'btn btn-blue' %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'layouts/companysidebar' %>
    </div>
  </div>
</div>